ENV["SIMPLECOV_COMMAND_NAME"] ||= "Cucumber"
require_relative "../../simplecov_setup"

# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.


require 'cucumber/rails'

# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail. This is a different from how
# your application behaves in the production environment, where an error page will
# be rendered instead.
#
# Sometimes we want to override this default behaviour and allow Rails to rescue
# exceptions and display an error page (just like when the app is running in production).
# Typical scenarios where you want to do this is when you test your error pages.
# There are two ways to allow Rails to rescue exceptions:
#
# 1) Tag your scenario (or feature) with @allow-rescue
#
# 2) Set the value below to true. Beware that doing this globally is not
# recommended as it will mask a lot of errors for you!
#
ActionController::Base.allow_rescue = false

# Remove/comment out the lines below if your app doesn't have a database.
# For some databases (like MongoDB and CouchDB) you may need to use :truncation instead.
begin
  DatabaseCleaner.strategy = :transaction
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

# Ensure database is migrated before running tests
# Note: db:prepare in CI should handle this, but we ensure it here as well
# For in-memory SQLite databases, migrations will run in Before hook (hooks.rb)
# For file-based databases, db:prepare should have already run migrations
begin
  # Establish connection first
  ActiveRecord::Base.connection
  
  # Check if we're using an in-memory database
  db_config = ActiveRecord::Base.connection_db_config.configuration_hash rescue nil
  database_path = db_config[:database] rescue nil
  
  if db_config && database_path != ':memory:'
    # For file-based databases (like in CI), ensure migrations are up to date
    begin
      migration_context = ActiveRecord::MigrationContext.new(ActiveRecord::Migrator.migrations_paths)
      # Check if migrations are pending and run them
      if migration_context.needs_migration?
        migration_context.migrate
      end
    rescue => migration_error
      # If migration check fails, try to continue - db:prepare should have handled it
      Rails.logger.warn "Migration check in env.rb: #{migration_error.message}" if defined?(Rails.logger)
    end
    
    # Verify critical tables exist
    unless ActiveRecord::Base.connection.table_exists?('users')
      # If users table doesn't exist, force migration
      migration_context = ActiveRecord::MigrationContext.new(ActiveRecord::Migrator.migrations_paths)
      migration_context.migrate
    end
  end
  # For in-memory databases, migrations run in Before hook in hooks.rb
rescue => e
  # For in-memory databases, migrations will run in Before hook
  # This is expected and not an error
  # For file-based databases, db:prepare should have handled migrations
  # Don't fail here - let the Before hook handle it
  Rails.logger.warn "Database setup in env.rb: #{e.message}" if defined?(Rails.logger)
end

# You may also want to configure DatabaseCleaner to use different strategies for certain features and scenarios.
# See the DatabaseCleaner documentation for details. Example:
#
#   Before('@no-txn,@selenium,@culerity,@celerity,@javascript') do
#     # { except: [:widgets] } may not do what you expect here
#     # as Cucumber::Rails::Database.javascript_strategy overrides
#     # this setting.
#     DatabaseCleaner.strategy = :truncation
#   end
#
#   Before('not @no-txn', 'not @selenium', 'not @culerity', 'not @celerity', 'not @javascript') do
#     DatabaseCleaner.strategy = :transaction
#   end
#

# Possible values are :truncation and :transaction
# The :transaction strategy is faster, but might give you threading problems.
# See https://github.com/cucumber/cucumber-rails/blob/master/features/choose_javascript_database_strategy.feature
Cucumber::Rails::Database.javascript_strategy = :truncation
